name: lonelyreminder
description: "An intelligent OCR-based event reminder app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages for our app
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  chrono: ^0.1.0
  
  # Utility Packages
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  intl: ^0.18.1 # For date formatting
  
  # UI
  cupertino_icons: ^1.0.6
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

  # Code quality
  flutter_lints: ^2.0.0

# This is the fix. We are forcing a specific version of the 'analyzer' package
# to resolve the conflict between isar_generator and flutter_test.
dependency_overrides:
  analyzer: '5.13.0'

flutter:
  uses-material-design: true
