name: lonelyreminder
description: "An intelligent OCR-based event reminder app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Packages for our app
  chrono_dart: ^2.0.2

  # Utility Packages
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  intl: ^0.18.1 # For date formatting
  http: ^1.2.1

  # UI
  cupertino_icons: ^1.0.6

  # Firebase and Google Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.9
  google_sign_in: ^6.2.1
  googleapis: ^12.0.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  get_storage: ^2.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8

  # Code quality
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
